### ISSUE TITLE
Please add contributors to the Google sign in repo

### ISSUE THREAD

**Issue by vonovak** [devfd/ZenStarter#1]
Hi! Me and couple other guys are trying hard to find you online and get in touch with you because of https://github.com/devfd/react-native-google-signin/issues/324

It would be great if you could add ownership rights to Kerumen who already has push rights, but he's too busy to maintain it and he cannot add more people to the repo :/

Do you think you could help us out here? Thanks a lot!

**Comment by devfd** [comment]
Hi, I think it is not possible because the project is not part of an organisation.

**Comment by devfd** [comment]
@vonovak it would be great to arrange the transfer of google-signin repo to react-native-community

let me know
